/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                /** @example ok */
                                status?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch full knowledge graph
         * @description Returns every knowledge page as a node and every relation between
         *     known pages as an edge. Designed to be called once per page load
         *     so the frontend can render the whole graph without additional
         *     round-trips.
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Comma-separated list of relation names to include. When
                     *     omitted, every relation is returned.
                     * @example skos:broader,dcterms:hasPart
                     */
                    relations?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Full graph data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Graph"];
                        };
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pages */
        get: {
            parameters: {
                query?: {
                    /** @description Title filter (substring unless `exact=true`) */
                    name?: string;
                    /** @description When `true`, the `name` filter must match exactly */
                    exact?: "true" | "false";
                    /** @description Maximum number of pages to return. `0` means no limit. */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of page summaries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                count?: number;
                                pages?: components["schemas"]["PageSummary"][];
                            };
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single page with relations */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Notion page UUID (dashed or undashed) */
                    id: components["parameters"]["PageID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Page"];
                        };
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pages/{id}/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a relation to a page
         * @description Creates a relation `{id} → target_id` with the given relation name.
         *     When a Jena endpoint is configured, Notion and Jena are updated
         *     atomically via a compensating transaction.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Notion page UUID (dashed or undashed) */
                    id: components["parameters"]["PageID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RelationRequest"];
                };
            };
            responses: {
                /** @description Relation added (or already present) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["RelationResult"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalError"];
            };
        };
        /**
         * Remove a relation from a page
         * @description Idempotent. If the target is already absent, the response body
         *     includes `already_absent: true` and no Notion API call is made.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Notion page UUID (dashed or undashed) */
                    id: components["parameters"]["PageID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RelationRequest"];
                };
            };
            responses: {
                /** @description Relation removed (or already absent) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["RelationResult"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Synchronize Notion to Jena
         * @description Only registered when a Jena endpoint is configured.
         *     - `full`: drops and re-inserts the entire named graph.
         *     - `incremental`: upserts only pages updated since the last sync.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @default incremental
                         * @enum {string}
                         */
                        mode?: "full" | "incremental";
                    };
                };
            };
            responses: {
                /** @description Sync result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["SyncResult"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                500: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare Notion and Jena state
         * @description Only registered when a Jena endpoint is configured. **Slow**:
         *     iterates every Notion page and runs multiple SPARQL queries
         *     against Jena. Not suitable for interactive polling.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Diff result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["SyncStatus"];
                        };
                    };
                };
                500: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PageSummary: {
            id?: string;
            name?: string;
            summary?: string;
            /** Format: date-time */
            last_edited_time?: string;
        };
        Page: {
            id?: string;
            name?: string;
            summary?: string;
            /** Format: date-time */
            last_edited_time?: string;
            relations?: {
                [key: string]: components["schemas"]["PageRef"][];
            };
        };
        PageRef: {
            id?: string;
            name?: string;
        };
        Graph: {
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
            meta?: components["schemas"]["GraphMeta"];
        };
        GraphNode: {
            id?: string;
            label?: string;
            summary?: string;
            /** @example concept */
            group?: string;
        };
        GraphEdge: {
            /** @description Stable edge identifier (`<source>|<relation>|<target>`) */
            id?: string;
            source?: string;
            target?: string;
            label?: string;
            relation?: string;
        };
        GraphMeta: {
            node_count?: number;
            edge_count?: number;
            relations?: string[];
        };
        /** @enum {string} */
        RelationName: "skos:broader" | "skos:narrower" | "dcterms:hasPart" | "dcterms:isPartOf" | "dcterms:requires" | "dcterms:isRequiredBy" | "dcterms:references" | "dcterms:isReferencedBy" | "skos:related" | "schema:previousItem" | "schema:nextItem";
        RelationRequest: {
            /** @description Target Notion page UUID */
            target_id: string;
            relation: components["schemas"]["RelationName"];
        };
        RelationResult: {
            linked?: boolean;
            unlinked?: boolean;
            from?: string;
            to?: string;
            relation?: components["schemas"]["RelationName"];
            jena_synced?: boolean;
            already_existed?: boolean;
            already_absent?: boolean;
        };
        SyncResult: {
            /** @enum {string} */
            mode?: "full" | "incremental";
            /** @description Number of pages successfully synced */
            synced?: number;
            /** @description Present only when one or more pages failed */
            errors?: string[];
        };
        SyncStatus: {
            consistent?: boolean;
            notion_only?: number;
            jena_only?: number;
            notion_only_details?: string[];
            jena_only_details?: string[];
        };
        ErrorResponse: {
            error?: {
                code?: string;
                message?: string;
            };
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Notion page UUID (dashed or undashed) */
        PageID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
